POST {{gateway_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "测试课程103",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": ""
}
###
GET {{gateway_host}}/content/teachplan/117/tree-nodes

###
GET {{gateway_host}}/system/dictionary/all

###
POST {{gateway_host}}/media/files
Content-Type: application/json

{
  "filename": "",
  "fileType": "001001",
  "auditStatus": ""
}

### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="1.jpg"
Content-Type: application/octet-stream

< e:/1.jpg

###
POST {{content_host}}/content/teachplan/association/media
Content-Type: application/json

{
  "mediaId": "",
  "fileName": "",
  "teachplanId": 0
}

### 课程发布
POST {{content_host}}/content/coursepublish/1